### ISSUE TITLE
Change "/team" to "/newteam"

### ISSUE THREAD

**Issue by abourke09** [learn-co-curriculum/basic-sinatra-forms-lab#33]
The post request should be from /newteam, not /team. This is how it's explained in the prior lessons and is the only way to make the tests pass. The form information comes from /newteam and gets passed to the /team page through post /newteam. Please see below and note that the solution code needs to be edited as well. 

Original: "Create a route that responds to a POST request at /team"
Corrected: "Create a route that responds to a POST request at /newteam"
*changed "/team" to "/newteam"

**Comment by DanielSeehausen** [comment]
Hi @abourke09 

Thank you for bringing this to our attention. 

This lab just recently received a minor facelift so perhaps this was addressed? Please reference the new solution branch and let me know if you still see a problem. 

Otherwise, I believe there is a mix up here between route/view/get/post:

While the erb file is `newteam.erb`, the post route we would like students to create, as well as the spec, are expecting `/team`. The `/newteam` route is for a GET request, which serves the erb and the form. The POST, which submitting the form submits, is for `/team`
